apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: shopsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: discovery.type
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: ES_JAVA_OPTS
        - name: xpack.security.enabled
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: xpack.security.enabled
