apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: shopsphere
type: Opaque
stringData:
  MONGODB_USERNAME: root
  MONGODB_PASSWORD: root
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
