apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: shopsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image:  e-commerce-microservice-platform-product-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081

          envFrom:
            - configMapRef:
                name: product-config
            - secretRef:
                name: product-secret
