apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  namespace: shopsphere
type: Opaque
stringData:
  MONGODB_USERNAME: root
  MONGODB_PASSWORD: root
  ELASTICSEARCH_USERNAME: elastic
  ELASTICSEARCH_PASSWORD: changeme
