apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: shopsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: e-commerce-microservice-platform-user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: user-config
            - secretRef:
                name: user-secret
