apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: shopsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: e-commerce-microservice-platform-api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gateway-config
            - secretRef:
                name: gateway-secret
