apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: shopsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: e-commerce-microservice-platform-order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-secret
