apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: shopsphere
type: Opaque
stringData:
  MONGODB_USERNAME: root
  MONGODB_PASSWORD: root
  STRIPE_SECRET_KEY: your_stripe_secret_key_here
